query GetAllPersonnels($search: String, $page: Int, $pageSize: Int) {
  personnels(search: $search, page: $page, pageSize: $pageSize) {
    items {
      id
      user {
        id
        firstName
        lastName
        email
      }
      roles {
        id
        name
      }
      matricule
      jobTitle
      contractType {
        id
        designation
        code
      }
      emailPro
      phoneNumber
      address
      dateHired
      isActive
      establishment {
        id
        name
      }
    }
    totalCount
    numPages
    currentPage
  }
}

query GetPersonnel($id: ID!) {
  personnel(id: $id) {
    id
    user {
      id
      firstName
      lastName
      email
    }
    roles {
      id
      name
    }
    establishment {
      id
      name
    }
    matricule
    jobTitle
    contractType {
      id
      designation
      code
    }
    emailPro
    phoneNumber
    address
    dateHired
    isActive
  }
}

query GetAllContractTypes {
  contractTypes {
    items {
      id
      designation
      code
      description
    }
  }
}

query GetContractType($id: ID!) {
  contractType(id: $id) {
    id
    designation
    code
    description
  }
}
