# Generated by Django 5.2.7 on 2026-04-16 18:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('hr', '0001_initial'),
        ('structure', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('installment_count', models.PositiveIntegerField(default=1, help_text='Nombre de tranches prévu pour ce frais')),
                ('status', models.CharField(choices=[('UNPAID', 'Impayé'), ('PARTIAL', 'Partiel'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='UNPAID', max_length=20)),
                ('category', models.CharField(choices=[('REGISTRATION', "Frais d'Inscription"), ('TUITION', 'Scolarité'), ('CANTEEN', 'Cantine'), ('TRANSPORT', 'Transport'), ('OTHER', 'Autre')], default='TUITION', max_length=50)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='students.enrollment')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement Bancaire'), ('CHECK', 'Chèque')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Numéro de reçu ou réf transaction', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.personnel')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='FeeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('REGISTRATION', "Frais d'Inscription"), ('TUITION', 'Scolarité'), ('CANTEEN', 'Cantine'), ('TRANSPORT', 'Transport'), ('OTHER', 'Autre')], default='TUITION', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_modality', models.CharField(choices=[('UNIQUE', 'Paiement Unique'), ('INSTALLMENTS', 'Paiement par Tranches')], default='UNIQUE', max_length=20)),
                ('installment_count', models.PositiveIntegerField(default=1, help_text='Nombre de tranches si applicable')),
                ('installment_period', models.CharField(blank=True, choices=[('MONTHLY', 'Mensuel'), ('TRIMESTRIAL', 'Trimestriel'), ('SEMESTRIAL', 'Semestriel')], default='MONTHLY', max_length=20, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.academicyear', verbose_name='Année Académique')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_fees', to='structure.classroom', verbose_name='Classe Spécifique')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='structure.level', verbose_name='Niveau')),
                ('students', models.ManyToManyField(blank=True, related_name='special_fees', to='students.student', verbose_name='Élèves Spécifiques')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Définition de Frais',
                'verbose_name_plural': 'Définitions de Frais',
                'unique_together': {('level', 'category', 'academic_year', 'establishment')},
            },
        ),
    ]
