# Generated by Django 5.2.7 on 2026-04-19 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_establishmentmembership'),
        ('finance', '0001_initial'),
        ('structure', '0002_alter_cycle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='structure.option', verbose_name='Option/Filière'),
        ),
        migrations.AlterUniqueTogether(
            name='feedefinition',
            unique_together={('level', 'option', 'category', 'academic_year', 'establishment')},
        ),
    ]
