# Generated by Django 5.2.7 on 2026-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_feedefinition_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='print_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fois que la facture/reçu a été imprimée'),
        ),
    ]
