# Generated by Django 5.2.7 on 2026-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feedefinition_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedefinition',
            name='installment_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de tranches si applicable'),
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='installment_period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensuel'), ('TRIMESTRIAL', 'Trimestriel'), ('SEMESTRIAL', 'Semestriel')], default='MONTHLY', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='payment_modality',
            field=models.CharField(choices=[('UNIQUE', 'Paiement Unique'), ('INSTALLMENTS', 'Paiement par Tranches')], default='UNIQUE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
