# Generated by Django 5.2.7 on 2026-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_print_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedefinition',
            name='custom_installments',
            field=models.JSONField(blank=True, help_text="Format: [{'tranche': 1, 'amount': 50000}, {'tranche': 2, 'amount': 25000}]", null=True),
        ),
    ]
