# Generated by Django 5.2.7 on 2026-03-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feedefinition_installment_count_and_more'),
        ('structure', '0011_academicperiod_created_by_user_and_more'),
        ('students', '0010_enrollment_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedefinition',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_fees', to='structure.classroom', verbose_name='Classe Spécifique'),
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_fees', to='students.student', verbose_name='Élève Spécifique'),
        ),
        migrations.AlterField(
            model_name='feedefinition',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.academicyear', verbose_name='Année Académique'),
        ),
        migrations.AlterField(
            model_name='feedefinition',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='structure.level', verbose_name='Niveau'),
        ),
    ]
