# Generated by Django 5.2.7 on 2026-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_feedefinition_classroom_feedefinition_student_and_more'),
        ('students', '0010_enrollment_created_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedefinition',
            name='student',
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='special_fees', to='students.student', verbose_name='Élèves Spécifiques'),
        ),
    ]
