# Generated by Django 5.2.7 on 2026-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feedefinition_deleted_at_feedefinition_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_installments',
            field=models.JSONField(blank=True, help_text="Format copié de FeeDefinition: [{'tranche': 1, 'amount': 50000}, {'tranche': 2, 'amount': 25000}]", null=True),
        ),
    ]
