# Generated by Django 5.2.7 on 2026-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_feedefinition_student_feedefinition_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installment_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de tranches prévu pour ce frais'),
        ),
    ]
