# Generated by Django 5.2.7 on 2026-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_custom_installments'),
        ('structure', '0005_alter_cycle_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedefinition',
            name='classroom',
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='group_fees', to='structure.classroom', verbose_name='Classes Spécifiques'),
        ),
    ]
