# Generated by Django 5.2.7 on 2025-12-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_create_enrollment_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
