# Generated by Django 5.2.7 on 2026-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollment_deleted_at_enrollment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('REGISTERED', 'Inscrit'), ('LEFT', 'Parti'), ('EXPELLED', 'Renvoyé')], default='PENDING', max_length=20),
        ),
    ]
