# Generated by Django 5.2.7 on 2026-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_legal_guardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardian',
            name='role',
            field=models.CharField(choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('TUTOR', 'Tuteur')], default='TUTOR', max_length=20),
        ),
    ]
