# Generated by Django 5.2.7 on 2026-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_guardian_is_legal_guardian_guardian_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='Identifiant unique de la puce NFC/RFID', max_length=50, null=True, unique=True),
        ),
    ]
