# Generated by Django 5.2.7 on 2025-12-20 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('students', '0004_implement_student_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='students',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(default='0000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Liste des allergies connues', null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Conditions médicales chroniques', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='students.student')),
            ],
            options={
                'verbose_name': 'santé élève',
                'verbose_name_plural': 'santé élèves',
            },
        ),
    ]
