# Generated by Django 5.2.7 on 2025-12-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_health_module_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='guardians', to='students.student'),
        ),
    ]
