# Generated by Django 5.2.7 on 2025-12-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_base_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
