# Generated by Django 5.2.7 on 2026-01-05 16:42

import apps.documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_guardian_first_name_guardian_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.documents.utils.document_upload_path),
        ),
    ]
