# Generated by Django 5.2.7 on 2026-04-18 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('profilmanagement', '0002_remove_user_establishment_remove_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False, help_text="Le propriétaire a tous les droits sur l'établissement", verbose_name='Est le propriétaire')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('invited', 'Invité'), ('revoked', 'Révoqué')], default='active', max_length=20, verbose_name='Statut')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.establishment', verbose_name='Établissement')),
                ('roles', models.ManyToManyField(blank=True, related_name='memberships', to='profilmanagement.role', verbose_name='Rôles contextuels')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre de l'établissement",
                'verbose_name_plural': 'Membres des établissements',
                'unique_together': {('user', 'establishment')},
            },
        ),
    ]
