# Generated by Django 5.2.7 on 2026-04-09 09:01

import apps.documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.documents.utils.document_upload_path),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='print_header',
            field=models.ImageField(blank=True, null=True, upload_to=apps.documents.utils.document_upload_path),
        ),
    ]
