# Generated by Django 5.2.7 on 2025-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
