# Generated by Django 5.2.7 on 2025-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_establishment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='country',
            field=models.CharField(blank=True, default='Cameroun', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='print_footer',
            field=models.TextField(blank=True, help_text='Texte légal en bas de page', null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='print_header',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/headers/'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF / Matricule'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
