# Generated by Django 5.2.7 on 2025-12-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_establishment_and_academicyear'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='establishment',
            unique_together={('name', 'city')},
        ),
    ]
