# Generated by Django 5.2.7 on 2026-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_establishment_deleted_at_establishment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='', help_text='Code technique unique (ex: mod-finance)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Définit si le module est débloqué par la licence'),
        ),
    ]
