# Generated by Django 5.2.7 on 2026-05-17 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_module_code_module_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('module_code', models.CharField(help_text='Code technique unique du module (ex: mod-finance)', max_length=100, verbose_name='Code du Module')),
                ('is_active', models.BooleanField(default=True, help_text='Définit si le module est débloqué par la licence', verbose_name='Est Actif')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.establishment', verbose_name='Établissement')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licence Établissement',
                'verbose_name_plural': 'Licences Établissements',
                'unique_together': {('establishment', 'module_code')},
            },
        ),
    ]
