# Generated by Django 5.2.7 on 2026-05-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenantlicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantlicense',
            options={'verbose_name': 'Licence Tenant', 'verbose_name_plural': 'Licences Tenants'},
        ),
        migrations.AlterUniqueTogether(
            name='tenantlicense',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantlicense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire (Owner)'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantlicense',
            unique_together={('user', 'module_code')},
        ),
        migrations.RemoveField(
            model_name='tenantlicense',
            name='establishment',
        ),
    ]
