# Generated by Django 5.2.7 on 2026-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tenantlicense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantlicense',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=list, help_text='Liste des tags/pages autorisés pour ce module. Si vide, toutes les pages du module sont autorisées.', verbose_name='Pages Autorisées'),
        ),
    ]
