# Generated by Django 5.2.7 on 2025-12-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_establishment'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('hourly_quota', models.PositiveIntegerField(default=0, help_text='Volume horaire annuel')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='structure.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='structure.subject')),
            ],
            options={
                'verbose_name': 'Matière par Niveau',
                'verbose_name_plural': 'Matières par Niveau',
                'ordering': ['level', 'subject'],
                'unique_together': {('level', 'subject')},
            },
        ),
    ]
