# Generated by Django 5.2.7 on 2026-04-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_establishmentmembership'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('name', 'establishment')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cycle',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code du cycle'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='option',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='structure.cycle', verbose_name='Cycle rattaché'),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('code', 'establishment'), ('name', 'establishment')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('name', 'parent', 'cycle', 'establishment')},
        ),
    ]
