# Generated by Django 5.2.7 on 2026-04-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_establishmentmembership'),
        ('structure', '0002_alter_cycle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('code', 'establishment'), ('name', 'establishment')},
        ),
    ]
