# Generated by Django 5.2.7 on 2026-04-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_cycle_has_options_option_classroom_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='levelsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='levelsubject',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='structure.option'),
        ),
        migrations.AlterUniqueTogether(
            name='levelsubject',
            unique_together={('level', 'subject', 'option')},
        ),
    ]
