# Generated by Django 5.2.7 on 2025-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_classroom_is_active_cycle_is_active_level_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, help_text="L'année en cours"),
        ),
    ]
