# Generated by Django 5.2.7 on 2026-05-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenantlicense'),
        ('structure', '0004_academiccycleconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('code', 'establishment'), ('name', 'establishment'), ('order', 'establishment')},
        ),
    ]
