# Generated by Django 5.2.7 on 2026-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_levelsubject_credits_subjectgroup_levelsubject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_optional',
        ),
        migrations.AddField(
            model_name='levelsubject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
