# Generated by Django 5.2.7 on 2026-01-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_room_options_room_capacity_room_establishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text="Date de rentrée spécifique pour ce cycle. Si vide, utilise la date de l'année.", null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_configs', to='structure.academicyear')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_configs', to='structure.cycle')),
            ],
            options={
                'verbose_name': 'Configuration Cycle/Année',
                'verbose_name_plural': 'Configurations Cycle/Année',
                'unique_together': {('academic_year', 'cycle')},
            },
        ),
    ]
