# Generated by Django 5.2.7 on 2026-07-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_remove_subject_is_optional_levelsubject_is_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='cycles',
            field=models.ManyToManyField(blank=True, related_name='periods', to='structure.cycle'),
        ),
    ]
