# Generated by Django 5.2.7 on 2026-02-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('structure', '0008_academiccycleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text="Définit si c'est la période de saisie actuelle")),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='structure.academicyear')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
            ],
            options={
                'verbose_name': 'Période Académique',
                'verbose_name_plural': 'Périodes Académiques',
                'ordering': ['academic_year', 'start_date'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
    ]
