# Generated by Django 5.2.7 on 2026-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_academicperiod_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Indique si la période est définitivement clôturée et verrouillée.'),
        ),
    ]
