# Generated by Django 5.2.7 on 2026-02-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('structure', '0009_academicperiod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('name', 'academic_year', 'establishment')},
        ),
    ]
