# Generated by Django 5.2.7 on 2026-01-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('hr', '0004_create_planning_model'),
        ('structure', '0006_create_planning_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(blank=True, help_text="Date de début d'intervention. Si vide, correspond au début de l'année scolaire.", null=True)),
                ('end_date', models.DateField(blank=True, help_text="Date de fin d'intervention. Si vide, correspond à la fin de l'année scolaire.", null=True)),
                ('hours_scheduled', models.IntegerField(default=0, help_text='Heures prévues pour ce module')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_assignments', to='structure.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_assignments', to='structure.classroom')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_assignments', to='structure.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_assignments', to='hr.teacher')),
            ],
            options={
                'verbose_name': 'affectation pédagogique',
                'verbose_name_plural': 'affectations pédagogiques',
                'ordering': ['-academic_year', 'classroom', 'subject'],
            },
        ),
    ]
