# Generated by Django 5.2.7 on 2026-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0001_create_planning_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'planning',
                'verbose_name_plural': 'plannings',
                'ordering': ['-created_at'],
            },
        ),
    ]
