# Generated by Django 5.2.7 on 2026-01-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('hr', '0004_create_planning_model'),
        ('pedagogy', '0002_create_planningdetail_model'),
        ('structure', '0006_create_planning_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['-date_start'], 'verbose_name': 'Planning', 'verbose_name_plural': 'Plannings'},
        ),
        migrations.RemoveField(
            model_name='planning',
            name='name',
        ),
        migrations.AddField(
            model_name='planning',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='nom',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_details', to='structure.classroom')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_details', to='hr.teacher')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_details', to='structure.subject')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pedagogy.planning')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_details', to='structure.room')),
            ],
            options={
                'verbose_name': 'Détail du Planning',
                'verbose_name_plural': 'Détails du Planning',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
