# Generated by Django 5.2.7 on 2026-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0002_planning_deleted_at_planning_is_deleted_and_more'),
        ('structure', '0006_levelsubject_credits_subjectgroup_levelsubject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='is_conge',
            field=models.BooleanField(default=False, help_text='Marque cette période comme étant un congé (Annule les cours)'),
        ),
        migrations.AddField(
            model_name='planning',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Planning récurrent (Emploi du temps de base)'),
        ),
        migrations.AddField(
            model_name='planning',
            name='is_specific',
            field=models.BooleanField(default=False, help_text="Planning ponctuel (Evénement, Semaine d'examens...)"),
        ),
        migrations.AddField(
            model_name='planning',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text="Classes concernées par ce planning (Laissez vide pour appliquer à tout l'établissement)", related_name='targeted_plannings', to='structure.classroom'),
        ),
        migrations.AddField(
            model_name='planningdetail',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Marque ce cours spécifique comme annulé (utile pour les absences)'),
        ),
    ]
