# Generated by Django 5.2.7 on 2026-02-05 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_create_planning_model'),
        ('pedagogy', '0003_alter_planning_options_remove_planning_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_assignments', to='hr.personnel'),
        ),
    ]
