# Generated by Django 5.2.7 on 2026-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0003_planning_is_conge_planning_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningdetail',
            name='rescheduled_to',
            field=models.DateField(blank=True, help_text='Date à laquelle le cours a été reporté', null=True),
        ),
    ]
