# Generated by Django 5.2.7 on 2026-02-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_teacher_personnel_ptr'),
        ('pedagogy', '0004_alter_teachingassignment_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='teacher',
            new_name='personnel',
        ),
        migrations.AlterField(
            model_name='planningdetail',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_details', to='hr.personnel'),
        ),
    ]
