# Generated by Django 5.2.7 on 2026-04-08 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='establishment',
            field=models.ForeignKey(default='53cd47b0-0983-4173-9876-9d6266f80816', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
