# Generated by Django 5.2.7 on 2026-01-05 14:53

import apps.documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.utils.document_upload_path),
        ),
    ]
