# Generated by Django 5.2.7 on 2026-04-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_deleted_at_document_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
