# Student and Enrollment Queries
query GetAllStudents($search: String, $classroomId: ID, $academicYearId: ID, $status: String, $page: Int, $pageSize: Int) {
  students(search: $search, classroomId: $classroomId, academicYearId: $academicYearId, status: $status, page: $page, pageSize: $pageSize) {
    items {
      id
      firstName
      lastName
      matricule
      photo
      dateOfBirth
      placeOfBirth
      gender
      address
      qrCodeBase64
      rfidUid
      health {
        id
        bloodGroup
        medicalConditions
        allergies
        emergencyContactName
        emergencyContactPhone
      }
      enrollments {
        id
        status
        isRepeater
        classroom {
          id
          name
          level {
            id
            name
          }
        }
        academicYear {
          id
          name
        }
      }
      guardians {
        id
        role
        firstName
        lastName
        phoneNumber
        profession
        isLegalGuardian
        user {
          firstName
          lastName
          email
        }
      }
    }
    totalCount
    numPages
  }
}

query GetStudent($id: ID!) {
  student(id: $id) {
    id
    matricule
    firstName
    lastName
    gender
    photo
    dateOfBirth
    placeOfBirth
    address
    qrCodeBase64
    rfidUid
    health {
      id
      bloodGroup
      allergies
      medicalConditions
      emergencyContactName
      emergencyContactPhone
    }
    enrollments {
      id
      status
      classroom {
        id
        name
        level {
          id
          name
        }
      }
      academicYear {
        id
        name
      }
    }
    guardians {
      id
      role
      firstName
      lastName
      phoneNumber
      profession
      isLegalGuardian
      user {
        firstName
        lastName
        email
      }
    }
    siblings {
      id
      matricule
      firstName
      lastName
      gender
      photo
      dateOfBirth
    }
  }
}

query GetAllEnrollments($search: String, $classroomId: ID, $academicYearId: ID, $status: String, $page: Int, $pageSize: Int) {
  enrollments(search: $search, classroomId: $classroomId, academicYearId: $academicYearId, status: $status, page: $page, pageSize: $pageSize) {
    items {
      id
      status
      enrollmentDate
      isRepeater
      student {
        id
        firstName
        lastName
        matricule
        photo
        dateOfBirth
        placeOfBirth
        gender
        qrCodeBase64
        rfidUid
      }
      classroom {
        id
        name
        level {
          id
          name
          cycle {
            id
            name
          }
        }
      }
      academicYear {
        id
        name
      }
    }
    totalCount
    numPages
  }
}
