# Generated by Django 5.2.7 on 2026-01-01 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('profilmanagement', '0009_user_establishment'),
        ('structure', '0005_academicyear_created_at_academicyear_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('matricule', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('VACATAIRE', 'Vacataire'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage')], default='CDI', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email_pro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Professionnel')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='profilmanagement.role', verbose_name="Rôle dans l'établissement")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personnel',
                'verbose_name_plural': 'personnels',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr.personnel')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité (ex: Maths)')),
                ('hours_per_week', models.IntegerField(default=0, verbose_name='Volume horaire hebdo')),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
            },
            bases=('hr.personnel',),
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hours_scheduled', models.IntegerField(default=0, help_text='Heures prévues pour ce module')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='structure.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='structure.classroom')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='structure.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.teacher')),
            ],
            options={
                'verbose_name': 'affectation pédagogique',
                'verbose_name_plural': 'affectations pédagogiques',
            },
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('user', 'establishment'), name='unique_personnel_per_establishment'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('matricule', 'establishment'), name='unique_personnel_matricule_per_establishment'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject', 'academic_year'), name='unique_assignment'),
        ),
    ]
