# Generated by Django 5.2.7 on 2026-04-16 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('profilmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, unique=True, verbose_name='Désignation')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'type de contrat',
                'verbose_name_plural': 'types de contrat',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email_pro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Professionnel')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True)),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='hr.contracttype', verbose_name='Type de contrat')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('roles', models.ManyToManyField(blank=True, related_name='personnels', to='profilmanagement.role', verbose_name="Rôles dans l'établissement")),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personnel',
                'verbose_name_plural': 'personnels',
                'constraints': [models.UniqueConstraint(fields=('user', 'establishment'), name='unique_personnel_per_establishment'), models.UniqueConstraint(fields=('matricule', 'establishment'), name='unique_personnel_matricule_per_establishment')],
            },
        ),
    ]
