# Generated by Django 5.2.7 on 2026-01-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'type de contrat',
                'verbose_name_plural': 'types de contrat',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='hr.contracttype', verbose_name='Type de contrat'),
        ),
    ]
