# Generated by Django 5.2.7 on 2026-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_contracttype_deleted_at_contracttype_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre'),
        ),
    ]
