# Generated by Django 5.2.7 on 2026-01-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_contracttype_alter_personnel_matricule_and_more'),
        ('profilmanagement', '0009_user_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='role',
        ),
        migrations.AddField(
            model_name='personnel',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='personnels', to='profilmanagement.role', verbose_name="Rôles dans l'établissement"),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='designation',
            field=models.CharField(max_length=150, unique=True, verbose_name='Désignation'),
        ),
    ]
