# Generated by Django 5.2.7 on 2026-01-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_personnel_role_personnel_roles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
