# Generated by Django 5.2.7 on 2026-02-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_create_planning_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='personnel_ptr',
        ),
    ]
