# Generated by Django 5.2.7 on 2026-02-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_teacher_personnel_ptr'),
        ('pedagogy', '0005_rename_teacher_teachingassignment_personnel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
