# Generated by Django 5.2.7 on 2026-04-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
