# Generated by Django 5.2.7 on 2025-12-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('profilmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.group', verbose_name='Groupes de permission'),
        ),
    ]
