# Generated by Django 5.2.7 on 2025-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('profilmanagement', '0002_alter_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='Permissions Explicites'),
        ),
    ]
