# Generated by Django 5.2.7 on 2025-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilmanagement', '0005_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('couleur', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'voiture',
                'verbose_name_plural': 'voitures',
                'ordering': ['-created_at'],
            },
        ),
    ]
