# Generated by Django 5.2.7 on 2025-12-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilmanagement', '0007_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='personne',
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
