# Generated by Django 5.2.7 on 2025-12-14 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_establishment'),
        ('profilmanagement', '0008_remove_contact_personne_delete_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.establishment', verbose_name='Établissement'),
        ),
    ]
