# Generated by Django 5.2.7 on 2026-01-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilmanagement', '0009_user_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
