# Generated by Django 5.2.7 on 2026-01-05 14:53

import apps.documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilmanagement', '0010_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.documents.utils.document_upload_path),
        ),
    ]
