# Generated by Django 5.2.7 on 2026-02-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('hr', '0006_delete_teacher'),
        ('structure', '0009_academicperiod'),
        ('students', '0009_alter_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('default_coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text="Coefficient par défaut appliqué à ce type d'épreuve", max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
            ],
            options={
                'verbose_name': "Type d'Évaluation",
                'verbose_name_plural': "Types d'Évaluation",
                'unique_together': {('name', 'establishment')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('CLASS', 'Classe'), ('LEVEL', 'Niveau'), ('ESTABLISHMENT', 'Établissement')], default='CLASS', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'Saisie en cours'), ('COMPLETED', 'Saisie terminée'), ('LOCKED', 'Verrouillée')], default='DRAFT', max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Possibilité de forcer une valeur différente du type par défaut', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, help_text='Note maximale (ex: 20, 100)', max_digits=5)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text="Durée de l'épreuve en minutes", null=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='structure.academicperiod')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='evaluations', to='structure.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_evaluations', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('levels', models.ManyToManyField(blank=True, related_name='evaluations', to='structure.level')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.room', verbose_name="Salle d'examen")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='structure.subject')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_evaluations', to='hr.personnel', verbose_name='Surveillants')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.evaluationtype')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue', max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False, help_text="Marquer si l'élève était absent à l'évaluation")),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='evaluations.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['evaluation', 'student'],
                'unique_together': {('student', 'evaluation')},
            },
        ),
    ]
