# Generated by Django 5.2.7 on 2026-03-22 13:25

import apps.evaluations.models.evaluation_subject
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('hr', '0001_initial'),
        ('structure', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('CLASS', 'Classe'), ('LEVEL', 'Niveau'), ('ESTABLISHMENT', 'Établissement')], default='CLASS', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'Saisie en cours'), ('COMPLETED', 'Saisie terminée'), ('LOCKED', 'Verrouillée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='structure.academicperiod')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'Évaluation",
                'verbose_name_plural': "Sessions d'Évaluation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('subject_file', models.FileField(blank=True, help_text="Sujet de l'épreuve (PDF/Image)", null=True, upload_to=apps.evaluations.models.evaluation_subject.generate_subject_filename)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('levels', models.ManyToManyField(blank=True, help_text='Niveaux concernés par cette épreuve', related_name='evaluation_subjects', to='structure.level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='evaluations.evaluationsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_subjects', to='structure.subject')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Épreuve d'Évaluation",
                'verbose_name_plural': "Épreuves d'Évaluation",
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text="Durée de l'épreuve en minutes", null=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.classroom', verbose_name='Classes concernées')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('levels', models.ManyToManyField(blank=True, help_text='Niveaux concernés par cette planification', related_name='evaluation_plannings', to='structure.level')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('evaluation_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='evaluations.evaluationsubject')),
            ],
            options={
                'verbose_name': "Planification d'Épreuve",
                'verbose_name_plural': "Planifications d'Épreuve",
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Code système (ex: CC, EXAM) pour le moteur de bulletin', max_length=20, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Poids par défaut dans le calcul de la moyenne de matière', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Type d'Évaluation",
                'verbose_name_plural': "Types d'Évaluation",
                'unique_together': {('name', 'establishment')},
            },
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='evaluation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='evaluations.evaluationtype'),
        ),
        migrations.CreateModel(
            name='EvaluationSupervision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='structure.classroom', verbose_name='Classe (Salle)')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='evaluations.evaluationsession')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervisions', to='hr.personnel', verbose_name='Surveillants')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Surveillance d'Évaluation",
                'verbose_name_plural': "Surveillances d'Évaluation",
                'ordering': ['date', 'classroom'],
                'unique_together': {('session', 'date', 'classroom', 'establishment')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluationsession',
            unique_together={('title', 'academic_period', 'establishment')},
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False, help_text="Marquer si l'élève était absent à l'évaluation")),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('evaluation_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='evaluations.evaluationsubject', verbose_name='Épreuve')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['evaluation_subject', 'student'],
                'unique_together': {('student', 'evaluation_subject', 'establishment')},
            },
        ),
    ]
