# Generated by Django 5.2.7 on 2026-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationplanning_deleted_at_and_more'),
        ('structure', '0004_academiccycleconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplanning',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.room', verbose_name='Salles physiques'),
        ),
        migrations.AddField(
            model_name='evaluationsubject',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='evaluation_subjects', to='structure.classroom', verbose_name='Classes concernées'),
        ),
    ]
