# Generated by Django 5.2.7 on 2026-02-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_evaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationtype',
            name='default_coefficient',
        ),
    ]
