# Generated by Django 5.2.7 on 2026-04-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluationplanning_rooms_and_more'),
        ('hr', '0003_personnel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubject',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_subjects_corrector', to='hr.personnel', verbose_name='Correcteur'),
        ),
        migrations.AddField(
            model_name='evaluationsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_subjects_responsible', to='hr.personnel', verbose_name='Enseignant Responsable'),
        ),
    ]
