# Generated by Django 5.2.7 on 2026-02-26 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('evaluations', '0004_evaluation_subject_file'),
        ('hr', '0006_delete_teacher'),
        ('structure', '0010_alter_academicperiod_unique_together'),
        ('students', '0009_alter_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['evaluation_subject', 'student'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('CLASS', 'Classe'), ('LEVEL', 'Niveau'), ('ESTABLISHMENT', 'Établissement')], default='CLASS', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'Saisie en cours'), ('COMPLETED', 'Saisie terminée'), ('LOCKED', 'Verrouillée')], default='DRAFT', max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='structure.academicperiod')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_evaluation_sessions', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='evaluations.evaluationtype')),
            ],
            options={
                'verbose_name': "Session d'Évaluation",
                'verbose_name_plural': "Sessions d'Évaluation",
                'ordering': ['-created_at'],
                'unique_together': {('title', 'academic_period', 'establishment')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('subject_file', models.FileField(blank=True, help_text="Sujet de l'épreuve (PDF/Image)", null=True, upload_to='evaluations/subjects/')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('levels', models.ManyToManyField(blank=True, help_text='Niveaux concernés par cette épreuve', related_name='evaluation_subjects', to='structure.level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='evaluations.evaluationsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_subjects', to='structure.subject')),
            ],
            options={
                'verbose_name': "Épreuve d'Évaluation",
                'verbose_name_plural': "Épreuves d'Évaluation",
                'unique_together': {('session', 'subject', 'establishment')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text="Durée de l'épreuve en minutes", null=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.classroom', verbose_name='Classes concernées')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.room', verbose_name="Salle d'examen")),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_plannings', to='hr.personnel', verbose_name='Surveillants')),
                ('evaluation_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='evaluations.evaluationsubject')),
            ],
            options={
                'verbose_name': "Planification d'Épreuve",
                'verbose_name_plural': "Planifications d'Épreuve",
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='evaluations.evaluationsubject', verbose_name='Épreuve'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'evaluation_subject', 'establishment')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='evaluation',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
