# Generated by Django 5.2.7 on 2026-05-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_establishment_deleted_at_establishment_is_deleted_and_more'),
        ('evaluations', '0004_evaluationsubject_corrector_and_more'),
        ('structure', '0004_academiccycleconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationsupervision',
            options={'ordering': ['date', 'room'], 'verbose_name': "Surveillance d'Évaluation", 'verbose_name_plural': "Surveillances d'Évaluation"},
        ),
        migrations.RemoveField(
            model_name='evaluationsubject',
            name='corrector',
        ),
        migrations.RemoveField(
            model_name='evaluationsubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='evaluationsupervision',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='structure.room', verbose_name='Salle'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationsupervision',
            unique_together={('session', 'date', 'room', 'establishment')},
        ),
        migrations.RemoveField(
            model_name='evaluationsupervision',
            name='classroom',
        ),
    ]
