# Generated by Django 5.2.7 on 2026-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_evaluationsupervision_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplanning',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Marque cet examen comme annulé'),
        ),
        migrations.AddField(
            model_name='evaluationplanning',
            name='rescheduled_to',
            field=models.DateField(blank=True, help_text="Date à laquelle l'examen a été reporté", null=True),
        ),
    ]
