# Generated by Django 5.2.7 on 2026-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_grade_options_evaluationsession_and_more'),
        ('structure', '0010_alter_academicperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplanning',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.level', verbose_name='Niveaux concernés'),
        ),
    ]
