# Generated by Django 5.2.7 on 2026-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluationplanning_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_absent',
        ),
        migrations.AddField(
            model_name='grade',
            name='absence_status',
            field=models.CharField(choices=[('NONE', 'Présent'), ('JUSTIFIED', 'Absence Justifiée (Neutre)'), ('UNJUSTIFIED', 'Absence Non-Justifiée (Zéro)')], default='NONE', help_text="Statut de présence à l'évaluation", max_length=20),
        ),
    ]
