# Generated by Django 5.2.7 on 2026-03-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluationplanning_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationsubject',
            name='coefficient',
        ),
    ]
