# Generated by Django 5.2.7 on 2026-03-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_establishment_unique_name_city'),
        ('evaluations', '0007_remove_evaluationsubject_coefficient'),
        ('hr', '0006_delete_teacher'),
        ('structure', '0010_alter_academicperiod_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationplanning',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='evaluationplanning',
            name='room',
        ),
        migrations.RemoveField(
            model_name='evaluationplanning',
            name='supervisors',
        ),
        migrations.CreateModel(
            name='EvaluationSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='structure.classroom', verbose_name='Classe (Salle)')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.establishment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='evaluations.evaluationsession')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervisions', to='hr.personnel', verbose_name='Surveillants')),
            ],
            options={
                'verbose_name': "Surveillance d'Évaluation",
                'verbose_name_plural': "Surveillances d'Évaluation",
                'ordering': ['date', 'classroom'],
                'unique_together': {('session', 'date', 'classroom', 'establishment')},
            },
        ),
    ]
