# Generated by Django 5.2.7 on 2026-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_remove_evaluationplanning_levels_and_more'),
        ('structure', '0010_alter_academicperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplanning',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.level', verbose_name='Niveaux concernés'),
        ),
        migrations.AlterField(
            model_name='evaluationplanning',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.classroom', verbose_name="Classes (Salles d'examen)"),
        ),
    ]
