# Generated by Django 5.2.7 on 2026-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_evaluationplanning_levels_and_more'),
        ('structure', '0010_alter_academicperiod_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationsubject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluationplanning',
            name='levels',
        ),
        migrations.AlterField(
            model_name='evaluationplanning',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='evaluation_plannings', to='structure.classroom', verbose_name='Classes concernées'),
        ),
    ]
