# Generated by Django 5.2.7 on 2026-03-04 05:57

import apps.evaluations.models.evaluation_subject
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_alter_evaluationsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsubject',
            name='subject_file',
            field=models.FileField(blank=True, help_text="Sujet de l'épreuve (PDF/Image)", null=True, upload_to=apps.evaluations.models.evaluation_subject.generate_subject_filename),
        ),
    ]
