# Generated by Django 5.2.7 on 2026-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_alter_evaluationsubject_subject_file'),
        ('structure', '0010_alter_academicperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplanning',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Niveaux concernés par cette planification', related_name='evaluation_plannings', to='structure.level'),
        ),
    ]
