# Generated by Django 5.2.7 on 2026-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_evaluationplanning_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'Saisie en cours'), ('COMPLETED', 'Saisie terminée'), ('LOCKED', 'Verrouillée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20),
        ),
    ]
