# Generated by Django 5.2.7 on 2026-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_alter_evaluationsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtype',
            name='code',
            field=models.CharField(blank=True, help_text='Code système (ex: CC, EXAM) pour le moteur de bulletin', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Poids par défaut dans le calcul de la moyenne de matière', max_digits=5),
        ),
    ]
