# Generated by Django 5.2.7 on 2026-03-10 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_remove_evaluationsession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
